# Generated by Django 3.2.7 on 2021-10-02 13:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(help_text='The name of the person', unique=True)),
                ('email', models.TextField(help_text='How to reach the person the kind way', null=True)),
                ('phone', models.TextField(help_text='How to reach the person the annoying way', null=True)),
                ('is_eta', models.BooleanField(help_text='If eta should pay for the stuff', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToMemberInvoice',
            fields=[
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12, primary_key=True, serialize=False, unique=True)),
                ('payed', models.BooleanField(default=False)),
                ('created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FarnellItem',
            fields=[
                ('id', django_extensions.db.fields.RandomCharField(blank=True, editable=False, length=12, primary_key=True, serialize=False, unique=True)),
                ('cost', models.FloatField(help_text='The amount to pay including VAT')),
                ('item_no', models.TextField(help_text='Item number farnell or TME')),
                ('item_desc', models.TextField(help_text='Description of the item, to make it easy for the payer to know what is payed for')),
                ('created', models.DateField(default=django.utils.timezone.now, help_text='When this item was added to the database')),
                ('item_count', models.IntegerField(help_text='How many of the item was purchased')),
                ('order_placed_at', models.DateTimeField(help_text='When the order was placed at farnell or TME')),
                ('invoice_number', models.TextField(help_text='The invoce number as paid by ETA. Used for manual digging')),
                ('person', models.ForeignKey(help_text='The person to pay', on_delete=django.db.models.deletion.CASCADE, to='app.person')),
                ('to_member_invoice', models.ForeignKey(help_text='The invoice sent to the member', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.tomemberinvoice')),
            ],
        ),
        migrations.AddConstraint(
            model_name='farnellitem',
            constraint=models.UniqueConstraint(fields=('item_no', 'invoice_number'), name='Item can only appear in same invoice once'),
        ),
    ]
