# Generated by Django 3.2.7 on 2021-10-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomemberinvoice',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
